- name: Install Spotify flatpak
  become: yes
  tags: spotify
  community.general.flatpak:
    name:  https://dl.flathub.org/repo/appstream/com.spotify.Client.flatpakref
    state: present


- name: Install Steam snap
  become: yes
  tags: steam
  community.general.snap:
    name:
      - steam
    state: present

- name: Enable i386 architecture
  become: yes
  tags: steam
  command: dpkg --add-architecture i386

- name: Steam extras (32bit libraries)
  become: yes
  tags: steam
  package:
    name:
      - libnvidia-gl-555:i386

- name: Install Codium snap
  become: yes
  tags: vscode
  community.general.snap:
    name:
      - code
    classic: true
    state: present

- name: Install Chrome
  become: yes
  tags: chrome
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

- name: Install Slack
  become: yes
  tags: slack
  apt:
    deb: https://downloads.slack-edge.com/desktop-releases/linux/x64/4.39.88/slack-desktop-4.39.88-amd64.deb