---
- hosts: all
  become: true
  pre_tasks:

    - name: Run updates
      tags: always
      package:
        upgrade: dist
        update_cache: yes
      when: ansible_os_family == "Debian"

- hosts: all
  become: true
  roles:
    - base
    - gnome
    - gui_apps
    - extra_apps
    - ppa
    - docker
    - nvidia
