- name: Install GUI apps
  become: yes
  package:
    name:
      - terminator
      - gimp
      - snapd
      - openconnect
      - network-manager-openconnect
      - network-manager-openconnect-gnome
      - calibre
      - transmission-gtk
    state: present

- name: Install fastfetch
  become: yes
  tags: fastfetch
  apt:
   deb: https://github.com/fastfetch-cli/fastfetch/releases/download/2.18.1/fastfetch-linux-amd64.deb
