- name: Install GNOME3 Desktop with extensions
  become: yes
  package:
    name:
      - ubuntu-desktop
      - task-gnome-desktop
      - gnome-shell-extensions
      - gnome-shell-extension-manager
      - flatpak
    state: present
