- name: Install packages
  become: yes
  package:
    name:
      - screen
      - git
      - nano
      - tmux
      - rsync
      - htop
      - python3
      - python3-pip
      - build-essential
      - fail2ban
    state: present
